.\"Comments go here
.\"Process this page with: groff -man -Tascii ipa-helper.1
.\"
.TH IPAHELPER 1 "MARCH 2014" Linux "IPAHELPER MAN PAGE"
.SH NAME
.B ipaHelper
\-\- script to help with examining and resigning ipa files
.SH SYNOPSIS
.B ipaHelper get [
mobileprovision files...
.B ]
.br
.B ipaHelper certs [
substring
.B ]
.br
.B ipaHelper profile [
ipa or mobileprovision file
.B ] [
options
.B ]
.br
.B ipaHelper info [
ipa or Info.plist file
.B ] [
options
.B ]
.br
.B ipaHelper summary [
ipa file
.B ]
.br
.B ipaHelper verify [
ipa file
.B ]
.br
.B ipaHelper resign [
ipa file
.B ] [
options
.B ]
.br
.B ipaHelper account [
options
.B ]
.br
.B ipaHelper upload [
ipa file
.B ]
.br
.B ipaHelper help [
-v
.B ] [
commands
.B ]
.br

.SH DESCRIPTION
.B GET

.B ipaHelper get [
mobileprovision files...
.B ]
.br

Moves mobileprovision files into the working directory.

If no profiles are specified, all .mobileprovision files in the Downloads folder are moved.

.B CERTS

.B ipaHelper certs [
substring
.B ]
.br

Displays information on all certificates in the keychain.

If a substring is provided, only certificates containing this substring are displayed.

.B PROFILE

.B ipaHelper profile [
ipa or mobileprovision file
.B ] [
options
.B ]
.br

Checks the profile of an .ipa file, or shows the information about a .mobileprovision file

If no .mobileprovision or .ipa file is provided, the first (alphabetically) ipa file in the working directory is used.
            
If no options are present, a summary of the provisioning profile is displayed.
                
.B Profile Options
                
.B -v, --verbose 
    display the entire profile in xml format

.B -e, --entitlements
    display the entitlements on the profile

.B -k
.I key
.B ,
.B --key
.I key
.br
    return the value for
.I key
in the profile

.B -l, --list 
    list all keys in the profile

.B -i, --id 
    display the application identifier
                
.B -c, --certificate
     display the certificate name
                
.B -t, --team 
    display the team name on the certificate
                
.B -x, --expiration 
    display the expiration date for the profile

.B INFO

.B ipaHelper info [
ipa or Info.plist file
.B ] [
-E
.B ] [
options
.B ]
.br

Checks the Info.plist of an .ipa file, or shows the information about an Info.plist file

If no Info.plist or .ipa file is provided, the first (alphabetically) ipa file in the working directory is used.
         
If no options are present, a summary of the Info.plist is displayed.
                
.B Info Options:

.B -E, --edit
    edit the Info.plist in vim

.B -v, --verbose 
    display the entire Info.plist in xml format

.B -k
.I key
.B ,
.B --key
.I key
.br
    return the value for
.I key
in the Info.plist    

.B -l, --list 
    list all keys in the Info.plist

.B -i, --identifier 
    display the CFBundleIdentifier

.B SUMMARY

.B ipaHelper summary [
ipa file
.B ]
.br

Displays profile and info.plist information about the ipa file.

If no ipa file is provided the first (alphabetically) ipa file in the working directory is used.

.B VERIFY

.B ipaHelper verify [
ipa file
.B ]
.br

Checks to make sure the necessary code signing components are in place for an ipa file.

If no ipa file is provided the first (alphabetically) ipa file in the working directory is used.

.B RESIGN

.B ipaHelper resign [
ipa file
.B ] [
options
.B ]
.br

Removes the code signature from the ipa file, and replaces it either with the first profile (alphabetically) in the directory with the ipa file.

Resigns the ipa file using the certificate on the profile and entitlements matching the profile, zips the resigned ipa file with the output filename.  If no output filename is provided, [ipa filename]-resigned.ipa is used.
    
If no .ipa file is provided, the first (alphabetically) ipa file in the working directory is used.
        
.B Resign Options:
        
.B -p
.I profile
.B ,
.B --profile
.I profile
.br
    use
.I profile
for resigning the ipa

.B -o
.I filename
.B ,
.B --output
.I filename
.br
    resign the ipa file as  
.I filename
instead of [ipa filename]-resigned.ipa

.B -d, --double-check 
    display information about the ipa, its Info.plist, and the provisioning profile and have be given an option to continue with the resign or quit

.B ACCOUNT

.B ipaHelper account [
options
.B ]
.br

Displays information about which certificates are linked with which iTunesConnect accounts.

.B Account Options:

.B -g
.I certificate
.B ,
.B --get
.I certificate
.br
    returns the iTunesConnect account linked to 
.I certificate
.br

.B -s
.I certificate account
.B ,
.B --set
.I certificate account
.br
    Links 
.I certificate
to the iTunesConnect
.I account
.br

.B -r
.I certificate
.B ,
.B --remove
.I certificate
.br
    Removes the link between
.I certificate
and its iTunesConnect account

.B UPLOAD

.B ipaHelper upload [
ipa file
.B ]
.br

Uploads the ipa file to iTunesConnect.  Asks for an iTunesConnect username if none is linked to the ipas certificate.

Asks for a password for this account.

If no .ipa file is provided, the first (alphabetically) ipa file in the working directory is used.

.B HELP

.B ipaHelper help [
-v
.B ] [
commands...
.B ]

Displays usage information for the different commands.

If -v option is present it shows the usage information for all of the commands.

.B Commands: 
    Get   Certs   Profile   Info   Summary   Verify   Resign   Account  Upload  Help

.SH AUTHOR
Marcus Smith
