.\"Comments go here
.\"Process this page with: groff -man -Tascii ipa-helper.1
.\"
.TH IPA-HELPER 1 "MARCH 2014" Linux "IPA-HELPER MAN PAGE"
.SH NAME
.B ipa\-helper
\-\- script to help with examining and resigning ipa files
.SH SYNOPSIS
.B ipaHelper.sh get [
mobileprovision files...
.B ]
.br
.B ipaHelper.sh certs [
pattern
.B ]
.br
.B ipaHelper.sh profile [
ipa or mobileprovision file
.B ] [
options
.B ]
.br
.B ipaHelper.sh info [
ipa or Info.plist file
.B ] [
options
.B ]
.br
.B ipaHelper.sh resign [
ipa file
.B ] [
output file
.B ] [
options
.B ]
.br
.B ipaHelper.sh help [
commands...
.B ]
.SH Description
add descriptions

.SH Options
add Options

.SH Author
Marcus Smith
