.\"Comments go here
.\"Process this page with: groff -man -Tascii ipa-helper.1
.\"
.TH IPAHELPER 1 "MARCH 2014" Linux "IPAHELPER MAN PAGE"
.SH NAME
.B ipaHelper
\-\- script to help with examining and resigning ipa files
.SH SYNOPSIS
.B ipaHelper get [
mobileprovision files...
.B ]
.br
.B ipaHelper certs [
pattern
.B ]
.br
.B ipaHelper profile [
ipa or mobileprovision file
.B ] [
options
.B ]
.br
.B ipaHelper info [
ipa or Info.plist file
.B ] [
options
.B ]
.br
.B ipaHelper resign [
ipa file
.B ] [
output file
.B ] [
options
.B ]
.br
.B ipaHelper help [
commands...
.B ] [
options
.B ]
.SH DESCRIPTION
add descriptions

.SH OPTIONS
add Options

.SH AUTHOR
Marcus Smith
