.\"Comments go here
.\"Process this page with: groff -man -Tascii ipa-helper.1
.\"
.TH IPAHELPER 1 "MARCH 2014" Linux "IPAHELPER MAN PAGE"
.SH NAME
.B ipaHelper
\-\- script to help with examining and resigning ipa files
.SH SYNOPSIS
.B ipaHelper get [
mobileprovision files...
.B ]
.br
.B ipaHelper certs [
substring
.B ]
.br
.B ipaHelper profile [
file
.B ] [
options
.B ]
.br
.B ipaHelper find [
file
.B ] [
options
.B ]
.br
.B ipaHelper info [
file
.B ] [
options
.B ]
.br
.B ipaHelper summary [
file
.B ] [
options
.B ]
.br
.B ipaHelper clean
.br
.B ipaHelper rezip [
outputfile
.B ]
.br
.B ipaHelper verify [
file
.B ]
.br
.B ipaHelper resign [
file
.B ] [
options
.B ]
.br
.B ipaHelper account [
options
.B ]
.br
.B ipaHelper upload [
ipa file
.B ]
.br
.B ipaHelper help [
-v
.B ] [
commands
.B ]
.br

.SH DESCRIPTION
.B GET

.B ipaHelper get [
mobileprovision files...
.B ]
.br

Moves mobileprovision files into the working directory.

If no profiles are specified, all .mobileprovision files in the Downloads folder are moved.

.B CERTS

.B ipaHelper certs [
substring
.B ]
.br

Displays information on all certificates in the keychain.

If a substring is provided, only certificates containing this substring are displayed.

.B PROFILE

.B ipaHelper profile [
file
.B ] [
options
.B ]
.br

Checks the profile of an ipa, app, xcarchive, or zip file containing an app file, or shows the information about a .mobileprovision file

If no file is provided, the first (alphabetically) ipa file in the working directory is used.
            
If no options are present, a summary of the provisioning profile is displayed.
                
.B Profile Options
                
.B -v, --verbose 
    display the entire profile in xml format

.B -e, --entitlements
    display the entitlements on the profile

.B -k
.I key
.B ,
.B --key
.I key
.br
    return the value for
.I key
in the profile

.B -l, --list 
    list all keys in the profile

.B -i, --id 
    display the application identifier
                
.B -c, --certificate
     display the certificate name
                
.B -t, --team 
    display the team name on the certificate
                
.B -x, --expiration 
    display the expiration date for the profile

.B FIND

.B ipaHelper find [
file
.B ] [
options
.B ]
.br

Looks for profiles saved in the users library matching the bundle ID of the ipa, app, xcarchive or zip file containing an app file. 

If no file is provided, the first (alphabetically) ipa file in the working directory is used.

.B Find Options:

.B -m
.I pattern
.B , --matching
.I pattern
.br 
    only displays profiles matching
.I pattern
.br

.B -n, --no-wildcard
    only displays profiles with exact matches to the bundle ID, and not matching wildcard profiles

.B -a, --all
    displays all profiles in the users library.  Ignores --matching and --no-wildcard options.

.B --json
    returns the profile information in a JSON dictionary

.B INFO

.B ipaHelper info [
file
.B ] [
options
.B ]
.br

Checks the Info.plist of an ipa, app, xcarchive, or zip file containing an app file, or shows the information about an Info.plist file

If no file is provided, the first (alphabetically) ipa file in the working directory is used.
         
If no options are present, a summary of the Info.plist is displayed.
                
.B Info Options:

.B -e
.I editor
.B , --edit
.I editor
.br 
    edit the Info.plist with
.I editor.
If no editor is provided, default $EDITOR is used

.B -v, --verbose 
    display the entire Info.plist in xml format

.B -k
.I key
.B ,
.B --key
.I key
.br
    return the value for
.I key
in the Info.plist    

.B -l, --list 
    list all keys in the Info.plist

.B -i, --identifier 
    display the CFBundleIdentifier

.B SUMMARY

.B ipaHelper summary [
file
.B ]
.br

Displays profile and info.plist information about an ipa, app, xcarchive, or zip file containing an app file.

If no file is provided the first (alphabetically) ipa file in the working directory is used.

.B Summary Options:

.B Options:
        
.B --json 
    return the summary information in a JSON dictionary.  Also adds the a key "AppDirectory" for the temporary unzipped app.
        
.B -dc,  --dont-clean 
    do not remove the temporary app directory after returning summary information

.B CLEAN

.B ipaHelper clean

Cleans temporary files left over from Summary command with the --dont-clean option

.B REZIP

.B ipaHelper rezip [
outputfile
.B ]

Rezips left over temporary files from Summary command with the --dont-clean option as 
.I outputfile

.I Outputfile
must be an app, ipa, or zip file.

.B VERIFY

.B ipaHelper verify [
file
.B ]
.br

Checks to make sure the necessary code signing components are in place for an ipa file.

If no file is provided the first (alphabetically) ipa file in the working directory is used.

.B RESIGN

.B ipaHelper resign [
file
.B ] [
options
.B ]
.br

Removes the code signature from an ipa, app, xcarchive, or zip file containing an app file, and replaces it either with the first profile (alphabetically) in the directory with the file.

Resigns the file using the certificate on the profile and entitlements matching the profile, zips the resigned ipa file with the output filename.  If no output filename is provided, [filename]-resigned.[filetype] is used.  The same filetype as the input filetype is used by default, except xcarchives resign as app files.
    
If no file is provided, the first (alphabetically) ipa file in the working directory is used.
        
.B Resign Options:
        
.B -p
.I profile
.B ,
.B --profile
.I profile
.br
    use
.I profile
for resigning the ipa

.B -o
.I filename
.B ,
.B --output
.I filename
.br
    resign the ipa file as  
.I filename
instead of [filename]-resigned.ipa

.B -d, --double-check 
    display information about the file, its Info.plist, and the provisioning profile and have be given an option to continue with the resign or quit

.B -f, --force
    overwrites output file on resign without asking.  Will not resign if App ID and Bundle IDs do not match

.B ACCOUNT

.B ipaHelper account [
options
.B ]
.br

Displays information about which certificates are linked with which iTunesConnect accounts.

.B Account Options:

.B -g
.I certificate
.B ,
.B --get
.I certificate
.br
    returns the iTunesConnect account linked to 
.I certificate
.br

.B -s
.I certificate account
.B ,
.B --set
.I certificate account
.br
    Links 
.I certificate
to the iTunesConnect
.I account
.br

.B -r
.I certificate
.B ,
.B --remove
.I certificate
.br
    Removes the link between
.I certificate
and its iTunesConnect account

.B UPLOAD

.B ipaHelper upload [
ipa file
.B ]
.br

Uploads the ipa file to iTunesConnect.  Asks for an iTunesConnect username if none is linked to the ipas certificate.

Asks for a password for this account.

If no .ipa file is provided, the first (alphabetically) ipa file in the working directory is used.

.B HELP

.B ipaHelper help [
-v
.B ] [
commands...
.B ]

Displays usage information for the different commands.

If -v option is present it shows the usage information for all of the commands.

.B Commands: 
    Get   Certs   Profile   Info   Summary   Verify   Resign   Account  Upload  Help

.SH AUTHOR
Marcus Smith
